#!/usr/bin/env bash
# installs nginx and configures it on a remote server

nginx_configs="/etc/nginx/sites-available/default"
old_path="/var/www/html"
new_path="/var/www"

sudo apt-get update
sudo apt-get install -y nginx
sudo service start nginx
sudo chown -R "$USER":"$USER" $nginx_configs
sudo sed -i "s|$old_path|$new_path|g" "$nginx_configs"
pid=$(pgrep nginx | head -n 1)
sudo kill -HUP "$pid"
