#!/usr/bin/env bash

current_date=$(date +'%d-%m-%Y')
sql_file="backup.sql"
tar_file="$current_date.tar.gz"
mysqldump --all-databases -u root --password="$1" > $sql_file
tar -czvf $tar_file $sql_file
