#!/usr/bin/env bash
# printing Best School 10 times using while
count=0
while [[ "$count" -lt 10 ]]
do
    if [[ "$count" -eq 8 ]];
	then
	    echo "Hi"
	else
        echo "Best School"
    fi
    (( count++ ))
done
