#!/usr/bin/env bash
# printing strings 10 times using while
count=1
while [[ "$count" -le 20 ]]
do
    echo "$count"
	case $count in
	    4)
		    echo "bad luck from China"
			;;
	    8)
		    echo "bad luck from Japan"
			;;
		17)
		    echo "bad luck from Italy"
			;;
		*)
		    ;;
		esac
    (( count++ ))
done
