#!/usr/bin/env bash
# printing strings 10 times using while
count=1
while [[ "$count" -le 20 ]]
do
    if [[ "$count" -eq 4 ]];
	then
	    echo "$count"
		echo "bad luck from China"
	elif [[ "$count" -eq 8 ]]
	then
	    echo $count
        echo "bad luck from Japan"
	elif [[ "$count" -eq 17 ]]
	then
	    echo $count
		echo "bad luck from Italy"
	else
        echo $count
    fi
    (( count++ ))
done
